task:
  env:
    HOME: /tmp # cargo needs it
    VERSION: nightly-2025-05-18
  name: FreeBSD 15.0-CURRENT amd64
  freebsd_instance:
    image_family: freebsd-15-0-snap
  setup_script:
    - pkg install -y git
    - git clone --depth=1 https://github.com/freebsd/freebsd-src.git $HOME/freebsd-src
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
    - . "$HOME/.cargo/env"
    - pkg install -y llvm19
    - rustup component add rust-src
    - cargo install cargo-make
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . "$HOME/.cargo/env"
    - export SYSDIR="$HOME/freebsd-src/sys"
    - cd drivers/hello
    - cargo make build-kmod
    - make clean && cargo clean
    - cd -
    - cd drivers/char
    - cargo make build-kmod
    - make clean && cargo clean
  before_cache_script: rm -rf $HOME/.cargo/registry/index
