[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem", "compiler-builtins-no-f16-f128"]

[build]
target = "../../kernel/x86_64-kernel-freebsd.json"
rustflags = [
    "-C", "panic=abort",
]
