[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem", "compiler-builtins-no-f16-f128"]

[build]
rustflags = ["-C", "panic=abort"]
target = "kernel/x86_64-kernel-freebsd.json"
target-dir = "kernel/target"
