[package]
name = "e1000"
version = "0.1.0"
edition = "2024"

[lib]
name = "hello"
crate-type = ["staticlib"]

[dependencies]
kernel = { path = "../../kernel" }
lazy_static = { version = "1", features = ["spin_no_std"] }
libc = { version = "0.2", default-features = false }
